### ISSUE TITLE
Restart build 1 on Travis CI

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/jq-feedstock#1]
One of its dependencies was being built when this build started. So, it was unable to build as its dependency was missing. Now that dependency is present and available.

However, I seem to be unable to restart the build. @ocefpaf also tried to restart the build, but was unable to either. Currently, I don't have commit privileges on this repo so am unable to get a new build started.

@pelson, if you could please restart the Travis CI build or create a new one, that would be very much appreciated. Thanks.

**Comment by pelson** [comment]
I've restarted https://travis-ci.org/conda-forge/conda-forge.github.io. That should create the qj team and give you the ability to restart. Let me know how that works out.

**Comment by jakirkham** [comment]
Thanks @pelson.

Still was unable to restart. Think it is a Travis CI bug. However, as I now have commit privileges, I can solve this through other means ( https://github.com/conda-forge/jq-feedstock/pull/2 ). Kind of hacky I suppose, but it should get the job done.
